### ISSUE TITLE
Cannot get satisfied results

### ISSUE THREAD

**Issue by bryanibit** [RansML/Bayesian_Hilbert_Maps#1]
I ran the ipython code and the final session of the code produces:
```
('shapes:', (383118, 4))
0th scan:
  N=380
('D=', 5600)
((380,), (380,), (380,), (380, 5601), (5601,))
Traceback (most recent call last):
  File "yu_test.py", line 65, in <module>
    bhm_mdl.fit(X, y)
  File "/home/ugv-yu/bryan/Bayesian_Hilbert_Maps/sbhm.py", line 123, in fit
    XMX[42042048204]
IndexError: index 42042048204 is out of bounds for axis 0 with size 380
```

**Comment by RansML** [comment]
Thanks for pointing out. Solved! Please pull the latest updates.
